# Methodologie

(1) Terreinbezoeken en overleg met plaatselijke beheerders naar de getijdestuwen op de Dijle in Mechelen (leren van het beheer aldaar: do’s and dont’s, etc.) en de Dender in Dendermonde, analyses van debieten en opmaak van grafieken van op- en afwaartse waterstanden, analyses van klepstanden bij verschillende debieten, overlegvergaderingen met het WL, opmaak van een voorstel voor aangepast stuwbeheer, etc.

(2) Potentieel moet overwogen worden om ter plaatse, in samenwerking met het WL, metingen uit te voeren onder verschillende debietscondities en op- en afwaartse waterstanden.
    Eventueel moet een schaalmodelstudie opgezet worden door het WL.
    Deze metingen op terrein (bij verschillende debieten) / een potentiële schaalmodelstudie zijn voorlopig nog niet mee opgenomen in de personeelsinschatting.
    De noodzaak en haalbaarheid van bepaalde metingen / een schaalmodelstudie zal bekeken en besproken worden met het WL in deelopdracht 1.
    Daarom wordt deelopdracht 2 voorlopig nog niet mee opgenomen in de personeelsinschatting.
